    # Project language
    language: php
    # Allows use container-based infrastructure
    sudo: false
    # Start mysql service
    services:
     - mysql
    # Cache composer packages so "composer install" is faster
    cache:
     directories:
       - $HOME/.composer/cache/files
    # Matrix to test in every php version
    matrix:
     # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
     fast_finish: true
     include:
       - php: 7.2
       - php: hhvm
     allow_failures:
       - php: hhvm
    # Define an environment variable
    env:
     - SYMFONY_VERSION="3.0.*" DB=mysql
    # Install composer dependencies,
    # Create database, schema and fixtures
    install:
     - composer install
     - cp .env.example .env
     - php artisan key:generate
     #- php bin/console doctrine:database:create --env=test
     #- php bin/console doctrine:schema:create --env=test
     #- php bin/console doctrine:fixtures:load -n --env=test
    # Run script
    script:
     - phpunit
    deploy:
        provider: codedeploy
        access_key_id: "AKIAXTC7R6IMR7PYMKGS"
        secret_access_key: "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"
        bucket: "jenkins-vcloud"
        key: latest/MyApp.zip
        bundle_type: zip
        application: MyApp
        deployment_group: MyDeploymentGroup
        on:
          branch: production
    # After a build, send email notification with the build results
    notifications:
     email: dhaval.joshi@viitor.cloud