    # Project language
    language: php
    # Allows use container-based infrastructure
    sudo: false
    # Start mysql service
    services:
     - mysql
    # Cache composer packages so "composer install" is faster
    cache:
     directories:
       - $HOME/.composer/cache/files
    # Matrix to test in every php version
    matrix:
     # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
     fast_finish: true
     include:
       - php: 7.2
       - php: hhvm
     allow_failures:
       - php: hhvm
    # Define an environment variable
    env:
     - SYMFONY_VERSION="3.0.*" DB=mysql
    # Install composer dependencies
    install:
     - composer install
     - cp .env.example .env
     - php artisan key:generate
     #- php bin/console doctrine:schema:create --env=test
     #- php bin/console doctrine:fixtures:load -n --env=test
     # Run script
     #script:
          #- phpunit
          #- zip -r latest *
          #- mkdir -p dpl_cd_upload
          #- mv latest.zip dpl_cd_upload/latest.zip
     #deploy:
       #- provider: s3
         #access_key_id: "AKIAXTC7R6IMR7PYMKGS"
         #secret_access_key: "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"
         #local_dir: dpl_cd_upload
         #skip_cleanup: true
         #bucket: jenkins-vcloud
         #region: ap-south-1
       #- provider: codedeploy
         #access_key_id: "AKIAXTC7R6IMR7PYMKGS"
         #secret_access_key: "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"
         #bucket: jenkins-vcloud
         #key: latest.zip
         #bundle_type: zip
         #application: jenkins-demo
         #deployment_group: jenkins-demo
         #region: ap-south-1
    # After a build, send email notification with the build results
    notifications:
     email: dhaval.joshi@viitor.cloud