    # Project language
    language: php
    # Allows use container-based infrastructure
    sudo: false
    # Start mysql service
    services:
     - mysql
    # Cache composer packages so "composer install" is faster
    cache:
     directories:
       - $HOME/.composer/cache/files
    # Matrix to test in every php version
    matrix:
     # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
     fast_finish: true
     include:
       - php: 7.2
       - php: hhvm
     allow_failures:
       - php: hhvm
    # Define an environment variable
    env:
     - SYMFONY_VERSION="3.0.*" DB=mysql
    before_script:
      - mkdir -p build/logs
    # Install composer dependencies,
    # Create database, schema and fixtures
    install:
     - composer install
     - composer require satooshi/php-coveralls
     - cp .env.example .env
     - php artisan key:generate
     #- php bin/console doctrine:schema:create --env=test
     #- php bin/console doctrine:fixtures:load -n --env=test
    script:
     - phpunit --coverage-clover build/logs/clover.xml
    after_success:
      - sh -c 'if [ &quot;$TRAVIS_PHP_VERSION&quot; != &quot;hhvm&quot; ]; then php vendor/bin/coveralls -v; fi;'
    # After a build, send email notification with the build results
    notifications:
     email: dhaval.joshi@viitor.cloud